// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJWxBwgmUpqnQevwBDH2ocaKrLstmSFg',
    appId: '1:246791349145:web:9977083a25270a76eee908',
    messagingSenderId: '246791349145',
    projectId: 'todolistflutterkrainet',
    authDomain: 'todolistflutterkrainet.firebaseapp.com',
    storageBucket: 'todolistflutterkrainet.appspot.com',
    measurementId: 'G-FB0HGK19DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA79jz00lLctOGWLhUr59U1I49vjIlxwS8',
    appId: '1:246791349145:android:06ff252950cb55f1eee908',
    messagingSenderId: '246791349145',
    projectId: 'todolistflutterkrainet',
    storageBucket: 'todolistflutterkrainet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7YCYF50BB4rjq7TZjPEcX7dkkAA_P6g',
    appId: '1:246791349145:ios:0c5b4e8be9e9dc4feee908',
    messagingSenderId: '246791349145',
    projectId: 'todolistflutterkrainet',
    storageBucket: 'todolistflutterkrainet.appspot.com',
    iosBundleId: 'com.example.toDoListForFlutterKrainetVacancy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaJWxBwgmUpqnQevwBDH2ocaKrLstmSFg',
    appId: '1:246791349145:web:84d35e44916c8d7feee908',
    messagingSenderId: '246791349145',
    projectId: 'todolistflutterkrainet',
    authDomain: 'todolistflutterkrainet.firebaseapp.com',
    storageBucket: 'todolistflutterkrainet.appspot.com',
    measurementId: 'G-LDEH7RKNCJ',
  );
}
